### ISSUE TITLE
Other folder settings shouldn't bleed over

### ISSUE THREAD

**Issue by WraithKenny** [soderlind/vscode-phpcbf#10]
Currently, the extension loops through all of the project's folders, and attempts to find the executable in all of them. On one hand, this is a nice redundancy, but on the other, it doesn't seem like correct behavior, if you have different configurations in each folder and would rather a mistake (like you forgot to run 'composer install' in one) to error out.

**Comment by soderlind** [comment]
Again, agree. Did it due to a misunderstanding on where to look for the file.
