### ISSUE TITLE
Stops working when used with git lens

### ISSUE THREAD

**Issue by ainsofs** [soderlind/vscode-phpcbf#33]
Hi,

Im using phpcbf for drupal development using the drupal/coder composer library. When I turn on  [git lens](https://github.com/eamodio/vscode-gitlens) my code is not formatted correctly (using Format Document option of vscode). When I disable git lens it works again as expected. I dont know if this is a compatibility issue with here or git lens so posting this issue on [both issue queues](https://github.com/eamodio/vscode-gitlens/issues/810).

**My machine**
Windows 10 Pro 64 bit

**My vscode settings**

```
  "phpcbf.enable": true,
  "phpcbf.executablePath": "./vendor/squizlabs/php_codesniffer/bin/phpcbf.bat",
  "phpcbf.documentFormattingProvider": true,
  "phpcbf.onsave": false,
  "phpcbf.standard": "C:\\Users\\ainsofs\\AppData\\Roaming\\Composer\\vendor\\drupal\\coder\\coder_sniffer\\Drupal",
  "[php]": {
    "editor.defaultFormatter": "persoderlind.vscode-phpcbf"
  },
```

**Comment by ghost** [comment]
Resolved in gitlens 9.9.3
