### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by liciniofs** [soderlind/vscode-phpcbf#4]
Hi Per,

I get a "PHP Warning:  file_put_contents(//phpcbf-fixed.diff): failed to open stream: Permission denied in ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php on line 277"

Any idea on how to solve this?

Thanks!

**Comment by liciniofs** [comment]
Nevermind, a reboot solved it.

**Comment by soderlind** [comment]
People reboot to seldom ;)
