### ISSUE TITLE
Not detecting WordPress runs on a custom ruleset

### ISSUE THREAD

**Issue by liciniofs** [soderlind/vscode-phpcbf#5]
Hi!

The title says it all... :)

It just formats as PSR2 although I added "phpcbf.standard" : "WordPress-Extra",

Also, "phpcbf.onsave" : true, does nothing...

Thanks!

**Comment by soderlind** [comment]
If you do, `phpcbf -i` from the command line, does it list WordPress-Extra ?

**Comment by liciniofs** [comment]
Yep. :)

which phpcs
~/.composer/vendor/bin/phpcs

which phpcbf
~/.composer/vendor/bin/phpcbf

phpcbf -i
The installed coding standards are MySource, PEAR, PHPCS, PSR1, PSR2, Squiz, Zend, WordPress, WordPress-Core, WordPress-Docs, WordPress-Extra and WordPress-VIP

Settings:
"phpcbf.standard": "WordPress-Extra",
"phpcbf.onsave" : true

**Comment by soderlind** [comment]
.. btw, please update to the lastest version

And, on not triggering onsave. It's an known issue, I'm looking into it ( it fails intermittently :/ )

**Comment by liciniofs** [comment]
Just updated. :)

Still not recognising WP Standard.

Although I don't think this update was meant to solve this. :)

**Comment by soderlind** [comment]
The most importaant part in the lastest version was fixing slow/hanging phpcbf. 

I'm installing phpcs/cbf into `~/.composer/vendor/bin/` now and will test if I can replicate the problem with using WordPress-Extra.

btw, does any of the other WordPress rules work for you ?

**Comment by liciniofs** [comment]
No, none.

Thanks!

**Comment by soderlind** [comment]
phpcs version 3.2.2 ?
php version ?

I assume you're on a *nix or macOS box ?

**Comment by liciniofs** [comment]
phpcs -> 2.9.1

PHP -> I'm using Vagrant with 5.5.9

**Comment by liciniofs** [comment]
Updated to phpcs version 3.2.2 

All is good. :)

**Comment by soderlind** [comment]
No problem, glad to help :)
