### ISSUE TITLE
phpcbf.documentFormattingProvider: false diables the extension

### ISSUE THREAD

**Issue by WraithKenny** [soderlind/vscode-phpcbf#9]
As far as I can tell, disabling the `phpcbf.documentFormattingProvider` option disables all of the other functionality, since the rest of the extension relies on  the `commands.executeCommand("editor.action.formatDocument")` call.

**Comment by WraithKenny** [comment]
The `commands.registerTextEditorCommand("phpcbf-soderlind")` should probably be available independently of  `documentFormattingProvider` via the Command Palette.

**Comment by soderlind** [comment]
I know. First extension, learning as I refactor.
